name: Docker Image CI

on:
  schedule:
    - cron: '0 18 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Optional strict host key checking
        echo "StrictHostKeyChecking no" >> ~/.ssh/config

    - name: Clone private repo
      run: |
        git clone -b 17.0 git@github.com:odoo/enterprise.git ./git-repos/enterprise


    - name: Log in to private registry
      run: |
        echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login registry.spinuphost.be -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build -t registry.spinuphost.be/odoo-17:$(date +%Y%m%d) .
    - name: Push the image
      run: docker push registry.spinuphost.be/odoo-18:$(date +%Y%m%d)

    - name: Cleanup workspace and Docker artifacts
      if: always()
      run: |
        echo "Cleaning up files..."
        rm -rf ./git-repos

        echo "Cleaning up dangling Docker images..."
        docker image prune -f

        echo "Cleaning up containers (if any stuck)..."
        docker container prune -f

        echo "Done."
