name: Build and Push Docker Image

on:
  schedule:
    # Every day at 6 PM UTC
    - cron: '03 15 * * *'


jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to private registry
      run: |
        echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login YOUR_REGISTRY_URL -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    - name: Build Docker image
      run: |
        IMAGE_NAME=your-image-name
        TAG=latest
        docker build -t registry.spinuphost.be/odoo-18:$(date +%Y%m%d) .

    - name: Push Docker image
      run: |
        IMAGE_NAME=your-image-name
        TAG=latest
        docker push registry.spinuphost.be/odoo-18:$(date +%Y%m%d)

